[package]
name = "esm-ui"
version = "0.1.0"
description = "eSports Manager desktop application"
authors = ["sturdy-robot"]
license = "GPL-3.0-or-later"
repository = "https://github.com/sturdy-robot/esports-manager"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "esm_ui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.6", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.10.3", features = [] }
tauri-plugin-log = "2"

esm-core = { path = "../../esm-core" }
esm-models = { path = "../../esm-models" }
esm-engine = { path = "../../esm-engine" }
esm-data = { path = "../../esm-data" }
esm-db = { path = "../../esm-db" }
esm-ai = { path = "../../esm-ai" }
